### ISSUE TITLE
Hi just implemented this on the typescript skeleton repo

### ISSUE THREAD

**Issue by geea-develop** [moshensky/aurelia-custom-common-files#6]
note: please add to installation info. you must install select2, moment, jquery, datetimepicker.
and include this as a plugin eg. aurelia.use.plugin('aurelia-custom-common-files');

**Comment by moshensky** [comment]
Hi, thank you. I've added those notes to the README.md. Please note that I plan to move different components to their own repos. You can check my latest playground with components downloading latest dev branch from here: https://github.com/aurelia-components/examples/tree/develop
